const slides=[...document.querySelectorAll('.slogans h1')];const dots=[...document.querySelectorAll('.dots button')];let current=0;function show(i){slides[current].classList.remove('active');dots[current].classList.remove('active');current=i;slides[current].classList.add('active');dots[current].classList.add('active')}dots.forEach((d,i)=>d.addEventListener('click',()=>show(i)));setInterval(()=>show((current+1)%slides.length),4800);
const topics=[['成年人的世界，真的只篩選、不教育嗎？','當一個人沒有符合期待，我們該陪他一起成長，還是承認彼此不適合？'],['不同的人生階段，會讓我們愛上不同的人嗎？','當工作、夢想或家庭成為生活重心，你選擇的伴侶會不會也悄悄跟著改變？'],['好感、喜歡、合適，根據過去的經驗，對你而言有什麼不同？','回頭看以前的關係，哪一刻你會分辨出只是有好感、真的喜歡，或是兩個人其實合適？'],['在愛裡，你更想得到成長，還是快樂？','你期待伴侶推著你成為更好的人，還是讓你安心做最原本的自己？'],['你曾為了被愛，改變到不再快樂嗎？','有沒有一段關係，讓你努力成為對方喜歡的樣子，最後卻離自己越來越遠？'],['你希望對方情緒穩定，是因為想被接住嗎？','當你累了、脆弱了，你會期待伴侶照顧你的情緒，還是希望彼此為自己負責？'],['除了外表，你最喜歡自己哪個部分？','如果不能談外在條件，你會用什麼特質，讓喜歡的人看見你的價值？'],['最費力的一次磨合，你們做了什麼？','那次磨合最後成功了嗎？如果成功，是什麼讓關係撐過去；如果沒有，又是在哪裡卡住了？']];document.querySelector('#topicGrid').innerHTML=topics.map((t,i)=>`<article><span>0${i+1}</span><h3>${t[0]}</h3><p>${t[1]}</p></article>`).join('');

document.querySelectorAll('.dimension-card').forEach(card=>{const toggle=()=>{const flipped=card.classList.toggle('is-flipped');card.setAttribute('aria-pressed',String(flipped))};card.addEventListener('click',toggle);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})});

document.querySelectorAll('.scratch-card').forEach(card=>{const canvas=card.querySelector('.scratch-layer');const button=card.querySelector('.scratch-reveal');const ctx=canvas.getContext('2d',{willReadFrequently:true});let drawing=false,last=null,revealed=false;const paint=()=>{if(revealed)return;const rect=card.getBoundingClientRect();const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.globalCompositeOperation='source-over';ctx.fillStyle=card.dataset.color;ctx.fillRect(0,0,rect.width,rect.height);ctx.fillStyle='rgba(255,255,255,.72)';ctx.font='800 12px "Noto Sans TC","PingFang TC",sans-serif';ctx.textAlign='left';ctx.fillText(card.dataset.kicker,32,44);ctx.fillStyle='#fff';ctx.font='800 29px "Noto Sans TC","PingFang TC",sans-serif';ctx.fillText(card.dataset.lineOne,32,150);ctx.fillText(card.dataset.lineTwo,32,194);ctx.fillStyle='rgba(255,255,255,.78)';ctx.font='700 13px "Noto Sans TC","PingFang TC",sans-serif';ctx.fillText('用手指或滑鼠刮開',32,rect.height-34)};const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};const scratch=(from,to)=>{ctx.globalCompositeOperation='destination-out';ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=46;ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke()};const reveal=()=>{revealed=true;card.classList.add('is-revealed')};const check=()=>{const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let clear=0,total=0;for(let i=3;i<data.length;i+=64){total++;if(data[i]<40)clear++}if(clear/total>.42)reveal()};canvas.addEventListener('pointerdown',e=>{drawing=true;last=point(e);canvas.setPointerCapture(e.pointerId);scratch(last,last)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const next=point(e);scratch(last,next);last=next});const stop=()=>{if(!drawing)return;drawing=false;last=null;check()};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);button.addEventListener('click',reveal);new ResizeObserver(paint).observe(card);paint()});

document.querySelectorAll('.coffee-stage').forEach(stage=>stage.addEventListener('click',()=>{const card=stage.closest('.coffee-card');if(!card.classList.contains('is-revealed'))return;card.classList.add('show-qr');stage.setAttribute('aria-pressed','true');stage.setAttribute('aria-label','咖啡券 QR Code 已顯示')}));

const moreSection=document.querySelector('#more');
if(moreSection){
  const directoryStyle=document.createElement('style');
  directoryStyle.textContent='.directory-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.directory-card{display:block;padding:24px;border:1px solid #e1e5f3;border-radius:24px;background:#fff;box-shadow:0 16px 36px #2457ff0d;transition:transform .25s,box-shadow .25s,border-color .25s}.directory-card:hover{transform:translateY(-3px);box-shadow:0 24px 48px #2457ff18;border-color:#cbd5ff}.directory-card small{color:var(--coral);font-size:12px;font-weight:900;letter-spacing:.12em}.directory-card h3{margin:8px 0 16px;font-size:22px;line-height:1.35;color:var(--navy)}.directory-card b{color:var(--blue)}.featured-directory{grid-column:1/-1;display:grid}.featured-directory h3{font-size:30px}.featured-directory p{margin:0 0 16px;color:var(--muted);line-height:1.8}@media(max-width:760px){.directory-grid{grid-template-columns:1fr}.directory-card{padding:22px}.directory-card h3{font-size:20px}.featured-directory{grid-template-columns:1fr}.featured-directory h3{font-size:26px}}';
  document.head.appendChild(directoryStyle);
  const directoryLinks=[
    ['Podcast','MBTI 情感經驗 Podcast 首頁','./'],
    ['Podcast','英文版首頁','index-en.html'],
    ['互動遊戲','吵完，還能好好愛嗎？','conflict-game/'],
    ['心理測驗','MBTI 感情互動測驗','mbti-love-test/'],
    ['心理測驗','8 題上班族壓力反應測驗','mbti-love-test/work-stress/'],
    ['媒合頁面','Elite Coffee Match','elite-coffee-match/'],
    ['生日互動','吹熄蠟燭，許一個願望','birthday-wish.html'],
    ['生日互動','生日願望英文版','birthday-wish-en.html'],
    ['餐飲地圖','台北牛肉麵地圖','taipei-beef-noodle-map/'],
    ['餐飲地圖','台北餐酒館指南','taipei-bistro-guide/']
  ];
  moreSection.innerHTML=`<div class="more-head"><p class="kicker coral">SITE DIRECTORY</p><h2>其他</h2><p>把目前所有互動頁、測驗、Podcast 與生活地圖整理在這裡，想玩哪一個可以直接開啟。</p></div><div class="more-grid directory-grid"><a class="more-card directory-card featured-directory" href="truth-or-dare-wheel/"><span class="more-icon" aria-hidden="true">↻</span><div><small>互動遊戲</small><h3>真心轉一圈</h3><p>先轉人生、感情或事業，再從喜怒哀樂 16 種情緒中抽出一題真心話或大冒險。</p><b>開始轉輪盤 →</b></div></a>${directoryLinks.map(([type,title,href])=>`<a class="directory-card" href="${href}"><small>${type}</small><h3>${title}</h3><b>開啟 →</b></a>`).join('')}</div>`;
}
